### ISSUE TITLE
too many plugins?

### ISSUE THREAD

**Issue by gAmUssA** [kpramesh2212/json2java-gradle-plugin#1]
hello, @kpramesh2212!
I would like to use gradle plugin to generate POJOs but I bit confused with variety of plugins out there.

this one vs https://github.com/eirnym/js2p-gradle 

It looks like your plugin much better documented and have some resent activity.
Kindly advise on the state of `jsonschema2pojo` stuff.
Thank you

**Comment by kpramesh2212** [comment]
@gAmUssA 

I forked the https://github.com/eirnym/js2p-gradle plugin mainly for 2 reason

1. Better support for kotlin based gradle build scripts

2. To solve a small defect during class generation. 
     
    https://github.com/eirnym/js2p-gradle plugin generates multiple classes for the same schema .


Feel free to use it and modify it and suggest improvements and I will try to address it as much as possible.

**Comment by gAmUssA** [comment]
Thank you, sir, @kpramesh2212 
I'm planning to build a few examples with JSON schema and payload for Apache Kafka® https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-json.html
I will reach out if I will face some roadblock. Keep up the great work!!! 

Cheers,
Vik
